### ISSUE TITLE
doesn't seem to work on xcelium UCD files

### ISSUE THREAD

**Issue by magreen-8da** [amiq-consulting/CoverageLens#1]
I'm running XCELIUMMAIN1903001 on openSUSE Tumbleweed:

```
xrun: *E,OPT2ND: option (-v) requires an argument.
TOOL:	xrun	19.03-s013: Exiting on Oct 15, 2019 at 17:00:51 PDT  (total: 00:00:00)
```

`Linux <hostname> 5.2.14-1-default #1 SMP Tue Sep 10 10:52:01 UTC 2019 (374b0ae) x86_64 x86_64 x86_64 GNU/Linux`

When I run this command:

`coverage_lens.sh -d ../../Cadence_source_code/cov_work/scope/test/icc_00000000_28a6bfee.ucd -g cvg_name ALUCoverGroup`

I get this result:
```
export LD_LIBRARY_PATH=/opt/cadence/XCELIUMMAIN1903001_lnx86/tools.lnx86/lib/64bit:/opt/cadence/XCELIUMMAIN1903001_lnx86/tools/lib:/linux_x86_64; ./coverage_lens -d ../../Cadence_source_code/cov_work/scope/test/icc_00000000_28a6bfee.ucd -g cvg_name ALUCoverGroup
Arg parser finished successfully!
UCISDB #0 @../../Cadence_source_code/cov_work/scope/test/icc_00000000_28a6bfee.ucd
	Name is []
```

I can see the results in imc. Are there extra steps required to get this to run on Xcelium?

**Comment by amiq-consulting** [comment]
Hello!

The `-g cvg_name` option requires an integer as parameter which represents the index of the covergroup in the UCDB tree. By invoking CoverageLens with this option, its output represents the name of the covergroup found at the specified index.

If you have more questions, please feel free to ask.
